FROM opencfd/openfoam-default:2312

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-setuptools \
    python3-dev \
    ca-certificates \
    curl \
    wget \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Etc/UTC

WORKDIR /root/app
COPY . /root/app

RUN python3 -m pip install --no-cache-dir -r requirements.txt

CMD ["bash", "-c", "python3 app/src/pipelines/training_transform.py"]
