name: Test and Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  container:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t ci_cd .

    - name: Run pytest in Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/root/app ci_cd pytest app/test

    - name: Run pylint in Docker container
      run: |
        docker run --rm -v ${{ github.workspace }}:/root/app ci_cd pylint app/src app/test